openapi: 3.0.2
info:
    title: New API
    version: 1.0.0
    description: A brand new API with no content.  Go nuts!
paths:
    /addresses:
        summary: Handle CRUD Operations on Address objects
        get:
            responses:
                '200':
                    $ref: '#/components/responses/Address'
            summary: Get a list of the available addresses
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Address'
                required: true
            responses:
                '201':
                    description: Address succesfully submitted.
            operationId: SubmitNewAddress
components:
    schemas:
        Address:
            title: Root Type for Address
            description: ''
            type: object
            properties:
                address:
                    type: array
                    items:
                        type: string
                city:
                    type: string
                state:
                    type: string
                zip:
                    type: string
            example:
                address:
                    - Cave 1A
                    - Batcave Ave
                city: Gotham
                state: NY
                zip: '12345'
    responses:
        Address:
            content:
                application/json:
                    schema:
                        type: array
                        items:
                            $ref: '#/components/schemas/Address'
            description: ''
